import "../src/task-1.ts"
import "../src/task-2.ts"
import "../src/task-3.ts"
import "../src/task-4.ts"
import "../src/task-5.ts"
import "../src/task-6.ts"
import "../src/task-7.ts"
import "../src/task-8.ts"